resolver 127.0.0.11 valid=10s ipv6=off;

server {
    listen 80;
    server_name swarka-i-voditel.ru www.swarka-i-voditel.ru;

    client_max_body_size 10M;

    location / {
        set $upstream_web web;
        proxy_pass http://$upstream_web:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}

server {
    listen 80;
    server_name admin.swarka-i-voditel.ru;

    client_max_body_size 10M;

    location / {
        set $upstream_admin admin;
        proxy_pass http://$upstream_admin:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}

server {
    listen 80;
    server_name api.swarka-i-voditel.ru;

    client_max_body_size 10M;

    location / {
        set $upstream_api api;
        proxy_pass http://$upstream_api:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
